const BACKEND_PROTOCOL = process.env.REACT_APP_BACKEND_PROTOCOL
const BACKEND_HOST = process.env.REACT_APP_BACKEND_HOST
const BACKEND_PORT = process.env.REACT_APP_BACKEND_PORT

const BASE_URL = `${BACKEND_PROTOCOL}://${BACKEND_HOST}:${BACKEND_PORT}`

export default BASE_URL